### ISSUE TITLE
Deprecated API

### ISSUE THREAD

**Issue by lazywalker** [cmacrae/homebrew-formulae#6]
Hi, there's a warning about deprecated api, would you fix it? thanks.

```ruby
Warning: Calling plist_options is deprecated! Use service.require_root instead.
Please report this issue to the cmacrae/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /usr/local/Homebrew/Library/Taps/cmacrae/homebrew-formulae/spacebar.rb:33
```

**Comment by cmacrae** [comment]
> Hi, there's a warning about deprecated api, would you fix it? thanks.
> 
> 
> 
> ```ruby
> 
> Warning: Calling plist_options is deprecated! Use service.require_root instead.
> 
> Please report this issue to the cmacrae/formulae tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
> 
>   /usr/local/Homebrew/Library/Taps/cmacrae/homebrew-formulae/spacebar.rb:33
> 
> ```
> 
> 

Want to submit a PR? :)
